### ISSUE TITLE
redesign around hooks

### ISSUE THREAD

**Issue by syucream** [syucream/ts_mruby#36]
Current impl can support only PRE_REMAP hook or doRemap(), so ts_mruby can't support some methods(`ATS::Headers_out#[]`, etc). In this issue I rethink about hooks to support those.

- [x] Create some designs.
- [x] Enable to separate init functions considering hooks.
- [x] Implement an example script.

**Comment by syucream** [comment]
Design 1: EventMachine style event handler.

```ruby
# similar to EventMachine?
module MyEventHandler
  #
  # SEND_REQUEST_HDR hook
  #
  def send_request_hdr
    hin = ATS::Headers_in.new
    hin['X-Foo'] = 'Bar'
  end

  #
  # READ_RESPONSE_HDR hook
  #
  def read_response_hdr
    hout = ATS::Headers_out.new

    # rewrite response body if origin server allows
    if (hout['X-Allow-Transform'])
      hout.delete 'X-Allow-Transform'
      f = ATS::Filter.new
      f.transform! do |body|
        body + 'rewritten by ts_mruby :D'
      end
    end
  end
end

# TODO: consider to how to register
ATS::EventSystem.register_handler MyEventHandler
```

**Comment by syucream** [comment]
fixed by https://github.com/syucream/ts_mruby/pull/74
